pipeline{
    agent {
label 'dockerslave1'
    }
stages{
    stage('hello'){
        steps{
            sh 'java -version'
            echo "get working directory"
            sh 'pwd'
            sh 'whoami'
        }
    }
}
}
